### ISSUE TITLE
Summonings 

### ISSUE THREAD

**Issue by Rhialtaulier** [parvusdomus/custos#48]
Congratulations and many many thanks for your great work on this ruleset!

I think I have noticed a little discrepancy with the rules. Your Summoning item (which I believe covers the invocations/indigitamenta) is based on the Virtutes for the roll, but according to page 38 of the corebook, it should be based on the Peritiae. (For instance, a Warrior with the Mars Victor Summoning will roll De Bello and not Coordinatio). Or maybe I am mistaken in my understanding of this item?

**Comment by parvusdomus** [comment]
Hello Rhialtaulier,

Thanks for your kind words.

You are absulutelly right, this one flew under our radar during the playtesting. I'll have this one fixed asap :)

Thanks for your feedback.

Regards

**Comment by parvusdomus** [comment]
Whops. spoke too fast :) sorry for the confusion. Indigatamenta (at least the basic ones) doesn't actually need a roll to work, just to spend the pietas and have the effect. I think I added the virtues because I was told that some advanced indigatamenta (in some of the newer supplements I don't have) were linked to a virtute. For the basic ones just select (Virtute: None).

In your example the Mars Victor summoning, you don't need to roll De Bello to activate it. Simply spend the pietas after doing a regular De Bello roll and you get to roll again and add the results. I'm afraid this part is not automated.

**Comment by Rhialtaulier** [comment]
Yes, you are right, it makes perfect sense and doesn't need to be automated. Well, thank you for your very quick response, sorry to have troubled you but it gave me the opportunity to say how glad I am you did this, and how good it looks!
